### ISSUE TITLE
https://umbel.org/ is advertising some casinos. I guess it is no longer associated with this project.

### ISSUE THREAD

**Issue by aucampia** [structureddynamics/UMBEL#10]
This is the current content there: ![image](https://user-images.githubusercontent.com/4481387/115860750-3f2a7800-a432-11eb-8cd9-4085e566e205.png)

Maybe consider getting an .eu.org domain instead, they are free and dont need renewal.

**Comment by TallTed** [comment]
@fgiasson, @mkbergman, @oroszgy

Maybe switch to github.io? Or just remove the links to the expired umbel.org?

**Comment by fgiasson** [comment]
Should be good now!
