### ISSUE TITLE
remove coatOfArms, has blazon

### ISSUE THREAD

**Issue by VladimirAlexiev** [structureddynamics/UMBEL#5]
http://mappings.dbpedia.org/index.php/OntologyProperty_Talk:CoatOfArms
Maybe we don't need this since we have "blazon", which is used in some 200 templates:
http://mappings.dbpedia.org/index.php?title=Special:Search&ns0=1&ns200=1&ns202=1&ns204=1&ns206=1&ns208=1&ns210=1&ns212=1&ns214=1&ns216=1&ns218=1&ns220=1&ns222=1&ns224=1&ns226=1&ns228=1&ns230=1&ns232=1&ns236=1&ns238=1&ns240=1&ns242=1&ns246=1&ns250=1&ns254=1&ns256=1&ns262=1&ns264=1&ns268=1&ns272=1&ns274=1&ns282=1&ns284=1&ns304=1&ns312=1&ns328=1&ns378=1&ns396=1&redirs=1&search=blazon&limit=250&offset=0

Cound someone with knowledge of heralrdy tell us whether they are the same?

**Comment by VladimirAlexiev** [comment]
Sorry, wrong project!

**Comment by fgiasson** [comment]
Are the few others DBpedia specific also on the wrong project's page? (seems that only your first issue is related to umbel)
